"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote

import environ
from colorlog import ColoredFormatter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Version

try:
    VERSION = (BASE_DIR / "VERSION").read_text(encoding="utf-8").strip()
except FileNotFoundError:
    VERSION = "dev"


# Environment

env = environ.Env()
if os.environ.get("SDC_ENV", "dev") == "dev":
    if (BASE_DIR.parent / ".env.dev").is_file():
        env.read_env(BASE_DIR.parent / ".env.dev")
    env.read_env(BASE_DIR.parent / ".env.dev.example")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG")

ALLOWED_HOSTS = ["localhost"] + env.list("DJANGO_ALLOWED_HOSTS")


## Deployment
# https://docs.djangoproject.com/en/5.2/howto/deployment/

if not DEBUG:
    SECURE_HSTS_SECONDS = 3600

    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    SECURE_HSTS_PRELOAD = True

    SECURE_SSL_REDIRECT = True

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SECURE_REDIRECT_EXEMPT = [r"^(api|events|ws)/healthz$"]

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True


# CSRF
# https://docs.djangoproject.com/en/5.2/ref/settings/#csrf-trusted-origins

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS")


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = env.list("DJANGO_CORS_ALLOWED_ORIGINS")

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "guardian",
    "django_celery_beat",
    "apps.auth",
    "apps.main",
    "apps.healthz",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

ASGI_APPLICATION = "backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": env("POSTGRES_HOST"),
        "PORT": env.int("POSTGRES_PORT"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "NAME": env("POSTGRES_DB"),
        "OPTIONS": {
            "pool": True,
        },
    },
}


# Cache
# https://docs.djangoproject.com/en/5.2/ref/settings/#caches


def redis_url(db):
    quoted_redis_user = quote(env("REDIS_USER"), safe="")
    quoted_redis_password = quote(env("REDIS_PASSWORD"), safe="")
    return f"redis://{quoted_redis_user}:{quoted_redis_password}@{env('REDIS_HOST')}:{env.int('REDIS_PORT')}/{db}"


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": redis_url(0),
    }
}


# Storage
# https://docs.djangoproject.com/en/5.2/ref/settings/#storages

STORAGE_S3_OPTIONS = {
    "endpoint_url": env("AWS_S3_ENDPOINT_URL"),
    "custom_domain": env("AWS_S3_CUSTOM_DOMAIN"),
    "url_protocol": env("AWS_S3_URL_PROTOCOL"),
    "access_key": env("AWS_ACCESS_KEY_ID"),
    "secret_key": env("AWS_SECRET_ACCESS_KEY"),
    "bucket_name": env("AWS_STORAGE_BUCKET_NAME"),
    "addressing_style": "path",
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": STORAGE_S3_OPTIONS
        | {
            "location": "media",
            "object_parameters": {"ContentDisposition": "attachment"},
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": STORAGE_S3_OPTIONS
        | {
            "location": "static",
        },
    },
}


# Session
# https://docs.djangoproject.com/en/5.2/ref/settings/#sessions

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"


# Authentication
# https://docs.djangoproject.com/en/5.2/topics/auth/

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "guardian.backends.ObjectPermissionBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Email
# https://docs.djangoproject.com/en/5.2/topics/email/

if not DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

    EMAIL_HOST = env("DJANGO_EMAIL_HOST")

    EMAIL_PORT = env.int("DJANGO_EMAIL_PORT")

    EMAIL_USE_TLS = env.bool("DJANGO_EMAIL_USE_TLS")

    EMAIL_USE_SSL = env.bool("DJANGO_EMAIL_USE_SSL")

    EMAIL_HOST_USER = env("DJANGO_EMAIL_HOST_USER")

    EMAIL_HOST_PASSWORD = env("DJANGO_EMAIL_HOST_PASSWORD")

    DEFAULT_FROM_EMAIL = env("DJANGO_DEFAULT_FROM_EMAIL")

else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = f"{env('AWS_S3_URL_PROTOCOL')}//{env('AWS_S3_CUSTOM_DOMAIN')}/static/"


# Media URL
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-url

MEDIA_URL = f"{env('AWS_S3_URL_PROTOCOL')}//{env('AWS_S3_CUSTOM_DOMAIN')}/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Logging
# https://docs.djangoproject.com/en/5.2/ref/settings/#logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "colored": {
            "()": ColoredFormatter,
            "format": "{log_color}{asctime} [{levelname:^8}] [{processName}({process}):{threadName}] {name}({filename}:{lineno}) - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "colored",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Django REST framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "dj_rest_auth.jwt_auth.JWTCookieAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/min",
        "user": "60/min",
    },
    "NUM_PROXIES": 1 if not DEBUG else 0,
}


# drf-spectacular
# https://drf-spectacular.readthedocs.io/

SPECTACULAR_SETTINGS = {}  # type:ignore


# django-allauth
# https://allauth.org/

ACCOUNT_ADAPTER = "apps.auth.adapter.AccountAdapter"

ACCOUNT_AUTHENTICATION_METHOD = "email"

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_EMAIL_VERIFICATION = "mandatory"


# dj-rest-auth
# https://dj-rest-auth.readthedocs.io/

REST_AUTH = {
    "REGISTER_SERIALIZER": "apps.auth.serializers.RegisterSerializer",
    "LOGIN_SERIALIZER": "apps.auth.serializers.LoginSerializer",
    "PASSWORD_CHANGE_SERIALIZER": "apps.auth.serializers.PasswordChangeSerializer",
    "PASSWORD_RESET_SERIALIZER": "apps.auth.serializers.PasswordResetSerializer",
    "PASSWORD_RESET_CONFIRM_SERIALIZER": "apps.auth.serializers.PasswordResetConfirmSerializer",
    "OLD_PASSWORD_FIELD_ENABLED": True,
    "LOGOUT_ON_PASSWORD_CHANGE": True,
    "USE_JWT": True,
    "JWT_AUTH_HTTPONLY": True,
    "JWT_AUTH_COOKIE": "access-token",
    "JWT_AUTH_REFRESH_COOKIE": "refresh-token",
    "JWT_AUTH_SECURE": not DEBUG,
    "JWT_AUTH_COOKIE_USE_CSRF": True,
    "JWT_AUTH_COOKIE_ENFORCE_CSRF_ON_UNAUTHENTICATED": True,
}


# Simple JWT
# https://django-rest-framework-simplejwt.readthedocs.io/

SIMPLE_JWT = {}  # type:ignore


# ALTCHA
# https://altcha.org/

ALTCHA_ALGORITHM = "PBKDF2/SHA-256"

ALTCHA_COST = 10_000

ALTCHA_HMAC_SECRET = env("DJANGO_ALTCHA_HMAC_SECRET")

ALTCHA_HMAC_KEY_SECRET = env("DJANGO_ALTCHA_HMAC_KEY_SECRET")

ALTCHA_CHALLENGE_TTL = 3_600


# Channels
# https://channels.readthedocs.io/

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [redis_url(1)],
        },
    },
}


# Celery
# https://docs.celeryq.dev/

CELERY_BROKER_URL = redis_url(2)

CELERY_RESULT_BACKEND = redis_url(3)

CELERY_TIMEZONE = TIME_ZONE


# Frontend

FRONTEND_URL = env("DJANGO_FRONTEND_URL")

FRONTEND_URLS = {
    "account_verify_email": f"{FRONTEND_URL}/account/verify-email?key={{key}}",
    "account_reset_password_confirm": f"{FRONTEND_URL}/account/reset-password-confirm?uid={{uid}}&token={{token}}",
}
