/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/root'
import { Route as appIndexRouteImport } from './app/index'
import { Route as featuresAuthPagesIndexRouteImport } from './features/auth/pages/index'
import { Route as featuresAuthPagesChangePasswordRouteImport } from './features/auth/pages/change-password'
import { Route as featuresAuthPagesLoginRouteImport } from './features/auth/pages/login'
import { Route as featuresAuthPagesLogoutRouteImport } from './features/auth/pages/logout'
import { Route as featuresAuthPagesResendEmailRouteImport } from './features/auth/pages/resend-email'
import { Route as featuresAuthPagesResetPasswordRouteImport } from './features/auth/pages/reset-password'
import { Route as featuresAuthPagesResetPasswordConfirmRouteImport } from './features/auth/pages/reset-password-confirm'
import { Route as featuresAuthPagesSignupRouteImport } from './features/auth/pages/signup'
import { Route as featuresAuthPagesVerifyEmailRouteImport } from './features/auth/pages/verify-email'
import { Route as featuresEditorPagesIndexRouteImport } from './features/editor/pages/index'

const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthPagesIndexRoute = featuresAuthPagesIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthPagesChangePasswordRoute =
  featuresAuthPagesChangePasswordRouteImport.update({
    id: '/account/change-password',
    path: '/account/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthPagesLoginRoute = featuresAuthPagesLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthPagesLogoutRoute = featuresAuthPagesLogoutRouteImport.update({
  id: '/account/logout',
  path: '/account/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthPagesResendEmailRoute =
  featuresAuthPagesResendEmailRouteImport.update({
    id: '/account/resend-email',
    path: '/account/resend-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthPagesResetPasswordRoute =
  featuresAuthPagesResetPasswordRouteImport.update({
    id: '/account/reset-password',
    path: '/account/reset-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthPagesResetPasswordConfirmRoute =
  featuresAuthPagesResetPasswordConfirmRouteImport.update({
    id: '/account/reset-password-confirm',
    path: '/account/reset-password-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresAuthPagesSignupRoute = featuresAuthPagesSignupRouteImport.update({
  id: '/account/signup',
  path: '/account/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const featuresAuthPagesVerifyEmailRoute =
  featuresAuthPagesVerifyEmailRouteImport.update({
    id: '/account/verify-email',
    path: '/account/verify-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const featuresEditorPagesIndexRoute =
  featuresEditorPagesIndexRouteImport.update({
    id: '/editor/',
    path: '/editor/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/account/change-password': typeof featuresAuthPagesChangePasswordRoute
  '/account/login': typeof featuresAuthPagesLoginRoute
  '/account/logout': typeof featuresAuthPagesLogoutRoute
  '/account/resend-email': typeof featuresAuthPagesResendEmailRoute
  '/account/reset-password': typeof featuresAuthPagesResetPasswordRoute
  '/account/reset-password-confirm': typeof featuresAuthPagesResetPasswordConfirmRoute
  '/account/signup': typeof featuresAuthPagesSignupRoute
  '/account/verify-email': typeof featuresAuthPagesVerifyEmailRoute
  '/account/': typeof featuresAuthPagesIndexRoute
  '/editor/': typeof featuresEditorPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/account/change-password': typeof featuresAuthPagesChangePasswordRoute
  '/account/login': typeof featuresAuthPagesLoginRoute
  '/account/logout': typeof featuresAuthPagesLogoutRoute
  '/account/resend-email': typeof featuresAuthPagesResendEmailRoute
  '/account/reset-password': typeof featuresAuthPagesResetPasswordRoute
  '/account/reset-password-confirm': typeof featuresAuthPagesResetPasswordConfirmRoute
  '/account/signup': typeof featuresAuthPagesSignupRoute
  '/account/verify-email': typeof featuresAuthPagesVerifyEmailRoute
  '/account': typeof featuresAuthPagesIndexRoute
  '/editor': typeof featuresEditorPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof appIndexRoute
  '/account/change-password': typeof featuresAuthPagesChangePasswordRoute
  '/account/login': typeof featuresAuthPagesLoginRoute
  '/account/logout': typeof featuresAuthPagesLogoutRoute
  '/account/resend-email': typeof featuresAuthPagesResendEmailRoute
  '/account/reset-password': typeof featuresAuthPagesResetPasswordRoute
  '/account/reset-password-confirm': typeof featuresAuthPagesResetPasswordConfirmRoute
  '/account/signup': typeof featuresAuthPagesSignupRoute
  '/account/verify-email': typeof featuresAuthPagesVerifyEmailRoute
  '/account/': typeof featuresAuthPagesIndexRoute
  '/editor/': typeof featuresEditorPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/change-password'
    | '/account/login'
    | '/account/logout'
    | '/account/resend-email'
    | '/account/reset-password'
    | '/account/reset-password-confirm'
    | '/account/signup'
    | '/account/verify-email'
    | '/account/'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/change-password'
    | '/account/login'
    | '/account/logout'
    | '/account/resend-email'
    | '/account/reset-password'
    | '/account/reset-password-confirm'
    | '/account/signup'
    | '/account/verify-email'
    | '/account'
    | '/editor'
  id:
    | '__root__'
    | '/'
    | '/account/change-password'
    | '/account/login'
    | '/account/logout'
    | '/account/resend-email'
    | '/account/reset-password'
    | '/account/reset-password-confirm'
    | '/account/signup'
    | '/account/verify-email'
    | '/account/'
    | '/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRoute: typeof appIndexRoute
  featuresAuthPagesChangePasswordRoute: typeof featuresAuthPagesChangePasswordRoute
  featuresAuthPagesLoginRoute: typeof featuresAuthPagesLoginRoute
  featuresAuthPagesLogoutRoute: typeof featuresAuthPagesLogoutRoute
  featuresAuthPagesResendEmailRoute: typeof featuresAuthPagesResendEmailRoute
  featuresAuthPagesResetPasswordRoute: typeof featuresAuthPagesResetPasswordRoute
  featuresAuthPagesResetPasswordConfirmRoute: typeof featuresAuthPagesResetPasswordConfirmRoute
  featuresAuthPagesSignupRoute: typeof featuresAuthPagesSignupRoute
  featuresAuthPagesVerifyEmailRoute: typeof featuresAuthPagesVerifyEmailRoute
  featuresAuthPagesIndexRoute: typeof featuresAuthPagesIndexRoute
  featuresEditorPagesIndexRoute: typeof featuresEditorPagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof featuresAuthPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/change-password': {
      id: '/account/change-password'
      path: '/account/change-password'
      fullPath: '/account/change-password'
      preLoaderRoute: typeof featuresAuthPagesChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof featuresAuthPagesLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/logout': {
      id: '/account/logout'
      path: '/account/logout'
      fullPath: '/account/logout'
      preLoaderRoute: typeof featuresAuthPagesLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/resend-email': {
      id: '/account/resend-email'
      path: '/account/resend-email'
      fullPath: '/account/resend-email'
      preLoaderRoute: typeof featuresAuthPagesResendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/account/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof featuresAuthPagesResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reset-password-confirm': {
      id: '/account/reset-password-confirm'
      path: '/account/reset-password-confirm'
      fullPath: '/account/reset-password-confirm'
      preLoaderRoute: typeof featuresAuthPagesResetPasswordConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/signup': {
      id: '/account/signup'
      path: '/account/signup'
      fullPath: '/account/signup'
      preLoaderRoute: typeof featuresAuthPagesSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-email': {
      id: '/account/verify-email'
      path: '/account/verify-email'
      fullPath: '/account/verify-email'
      preLoaderRoute: typeof featuresAuthPagesVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor/'
      preLoaderRoute: typeof featuresEditorPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRoute: appIndexRoute,
  featuresAuthPagesChangePasswordRoute: featuresAuthPagesChangePasswordRoute,
  featuresAuthPagesLoginRoute: featuresAuthPagesLoginRoute,
  featuresAuthPagesLogoutRoute: featuresAuthPagesLogoutRoute,
  featuresAuthPagesResendEmailRoute: featuresAuthPagesResendEmailRoute,
  featuresAuthPagesResetPasswordRoute: featuresAuthPagesResetPasswordRoute,
  featuresAuthPagesResetPasswordConfirmRoute:
    featuresAuthPagesResetPasswordConfirmRoute,
  featuresAuthPagesSignupRoute: featuresAuthPagesSignupRoute,
  featuresAuthPagesVerifyEmailRoute: featuresAuthPagesVerifyEmailRoute,
  featuresAuthPagesIndexRoute: featuresAuthPagesIndexRoute,
  featuresEditorPagesIndexRoute: featuresEditorPagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
